import React, { createContext, useContext, useEffect, useState } from "react";
import { useAuth } from "./auth";

export const LANGUAGES = [
  { code: "en", label: "English", flag: "🇬🇧" },
  { code: "nl", label: "Nederlands", flag: "🇳🇱" },
  { code: "de", label: "Deutsch", flag: "🇩🇪" },
  { code: "fr", label: "Français", flag: "🇫🇷" },
  { code: "es", label: "Español", flag: "🇪🇸" },
];

const dict = {
  en: {
    nav: { dashboard: "Dashboard", quotes: "Quotes", invoices: "Invoices", clients: "Clients", billing: "Billing", settings: "Settings", new_quote: "New quote", logout: "Log out", free_plan: "Free plan", pro_plan: "Pro plan" },
    dash: { title: "Dashboard", total_quotes: "Total quotes", sent: "Sent", accepted: "Accepted", declined: "Declined", paid_revenue: "Paid revenue", unpaid: "Unpaid", overdue: "Overdue", recent_quotes: "Recent quotes", view_all: "View all", no_quotes: "No quotes yet. Create your first quote to get started.", quotes_used: "quotes used on the Free plan", upgrade_pro: "Upgrade to Pro" },
    quote: { title: "Quotes", new: "New quote", edit: "Edit quote", search_ph: "Search by client or quote number", empty: "No quotes yet. Create your first quote.", no_match: "No quotes match your filters.", number: "Number", client: "Client", status: "Status", created: "Created", total: "Total", subtotal: "Subtotal", vat: "VAT", discount: "Discount", project: "Project", project_ph: "Describe the project briefly", line_items: "Line items", add_item: "Add item", description: "Description", qty: "Qty", unit_price: "Unit price", amount: "Amount", notes: "Notes", notes_ph: "Optional notes (payment terms, validity, etc.)", summary: "Summary", create: "Create quote", save: "Save changes", back: "Back", pdf: "PDF", send: "Send", sending: "Sending…", convert_to_invoice: "Convert to invoice", convert_ready: "Ready to invoice?", convert_desc: "This quote was accepted. Convert it to an invoice in one click.", open_invoice: "Open invoice", status_block: "Status", status_desc: "Update the status after client response", mark_accepted: "Mark accepted", mark_declined: "Mark declined", reset_draft: "Reset to draft", danger: "Danger zone", delete: "Delete quote", bill_to: "Bill to", select_client: "Select client (optional)", new_client: "— New client —", client_name: "Client name", client_email: "Client email", accent_color: "Accent color", applied_pdf: "Applied to the PDF header" },
    discount: { title: "Discount", applied_before: "Applied before VAT", type: "Type", value: "Value", off: "Off", none: "No discount", percent: "Percentage (%)", fixed: "Fixed amount (€)" },
    invoice: { title: "Invoices", search_ph: "Search by client or invoice number", empty: "No invoices yet. Convert an accepted quote into an invoice.", no_match: "No invoices match your filters.", number: "Number", due_date: "Due date", revenue: "Total revenue", count: "Invoices", payment: "Payment", default_due: "Default 30 days after creation", mark_paid: "Mark as paid", paid_on: "Paid on", linked_quote: "Linked quote", danger: "Danger zone", delete: "Delete invoice" },
    clients: { title: "Clients", add: "Add client", new: "New client", edit: "Edit client", empty: "No clients yet. Add one to get started.", name: "Name", email: "Email", phone: "Phone", company: "Company", address: "Address", save: "Save", cancel: "Cancel" },
    settings: { title: "Settings", save: "Save changes", saving: "Saving…", company_info: "Company information", company_name: "Company name", vat_number: "VAT number", phone: "Phone", bank: "Bank account", address: "Address", signature: "Email signature", signature_help: "Appears at the bottom of every quote email and PDF.", logo: "Company logo", no_logo: "No logo", upload_logo: "Upload logo", account: "Account", plan: "Plan", pro_unlim: "Pro — unlimited", free_limit: "Free — 3 quotes max", preferences: "Preferences", language: "Language", accent_color: "Brand color", color_help: "Used in the header of your quote and invoice PDFs." },
    billing: { title: "Billing", free: "Free", pro: "Pro", per_month: "/month", current: "Current plan", active: "Active", up_free: ["Up to 3 quotes", "PDF export", "Email delivery", "Client management"], up_pro: ["Unlimited quotes", "Unlimited invoices", "Premium PDF layouts", "All Free features"], upgrade: "Upgrade to Pro", redirecting: "Redirecting…", confirming: "Confirming your payment…", test_note: "Test environment uses Stripe test card 4242 4242 4242 4242. No real charges." },
    auth: { welcome: "Welcome back", subtitle: "Log in to manage your quotes", create_acc: "Create your account", create_sub: "Start sending professional quotes in minutes", email: "Email", password: "Password", name: "Name", signin: "Sign in", signing: "Signing in…", creating: "Creating…", create_btn: "Create account", new_to: "New to Quotify?", create_link: "Create account", already: "Already registered?", signin_link: "Sign in" },
  },
  nl: {
    nav: { dashboard: "Dashboard", quotes: "Offertes", invoices: "Facturen", clients: "Klanten", billing: "Abonnement", settings: "Instellingen", new_quote: "Nieuwe offerte", logout: "Uitloggen", free_plan: "Gratis", pro_plan: "Pro" },
    dash: { title: "Dashboard", total_quotes: "Offertes totaal", sent: "Verzonden", accepted: "Geaccepteerd", declined: "Afgewezen", paid_revenue: "Betaalde omzet", unpaid: "Openstaand", overdue: "Vervallen", recent_quotes: "Recente offertes", view_all: "Bekijk alles", no_quotes: "Nog geen offertes. Maak je eerste offerte om te beginnen.", quotes_used: "offertes gebruikt van het gratis plan", upgrade_pro: "Upgrade naar Pro" },
    quote: { title: "Offertes", new: "Nieuwe offerte", edit: "Offerte bewerken", search_ph: "Zoek op klant of offertenummer", empty: "Nog geen offertes. Maak je eerste offerte.", no_match: "Geen offertes gevonden.", number: "Nummer", client: "Klant", status: "Status", created: "Datum", total: "Totaal", subtotal: "Subtotaal", vat: "BTW", discount: "Korting", project: "Project", project_ph: "Beschrijf het project kort", line_items: "Regelitems", add_item: "Item toevoegen", description: "Omschrijving", qty: "Aantal", unit_price: "Stukprijs", amount: "Bedrag", notes: "Notities", notes_ph: "Optionele notities (betaalvoorwaarden, geldigheid, enz.)", summary: "Samenvatting", create: "Offerte aanmaken", save: "Wijzigingen opslaan", back: "Terug", pdf: "PDF", send: "Verzenden", sending: "Verzenden…", convert_to_invoice: "Naar factuur omzetten", convert_ready: "Klaar om te factureren?", convert_desc: "Deze offerte is geaccepteerd. Zet hem met één klik om in een factuur.", open_invoice: "Factuur openen", status_block: "Status", status_desc: "Werk de status bij na reactie van de klant", mark_accepted: "Markeer als geaccepteerd", mark_declined: "Markeer als afgewezen", reset_draft: "Terug naar concept", danger: "Gevarenzone", delete: "Offerte verwijderen", bill_to: "T.a.v.", select_client: "Selecteer klant (optioneel)", new_client: "— Nieuwe klant —", client_name: "Klantnaam", client_email: "E-mail klant", accent_color: "Accentkleur", applied_pdf: "Wordt toegepast op de PDF-header" },
    discount: { title: "Korting", applied_before: "Toegepast vóór BTW", type: "Type", value: "Waarde", off: "Korting", none: "Geen korting", percent: "Percentage (%)", fixed: "Vast bedrag (€)" },
    invoice: { title: "Facturen", search_ph: "Zoek op klant of factuurnummer", empty: "Nog geen facturen. Zet een geaccepteerde offerte om in een factuur.", no_match: "Geen facturen gevonden.", number: "Nummer", due_date: "Vervaldatum", revenue: "Totale omzet", count: "Facturen", payment: "Betaling", default_due: "Standaard 30 dagen na aanmaak", mark_paid: "Markeer als betaald", paid_on: "Betaald op", linked_quote: "Gekoppelde offerte", danger: "Gevarenzone", delete: "Factuur verwijderen" },
    clients: { title: "Klanten", add: "Klant toevoegen", new: "Nieuwe klant", edit: "Klant bewerken", empty: "Nog geen klanten. Voeg er een toe om te beginnen.", name: "Naam", email: "E-mail", phone: "Telefoon", company: "Bedrijf", address: "Adres", save: "Opslaan", cancel: "Annuleren" },
    settings: { title: "Instellingen", save: "Wijzigingen opslaan", saving: "Opslaan…", company_info: "Bedrijfsgegevens", company_name: "Bedrijfsnaam", vat_number: "BTW-nummer", phone: "Telefoon", bank: "Bankrekening", address: "Adres", signature: "E-mailhandtekening", signature_help: "Verschijnt onderaan elke offerte-e-mail en PDF.", logo: "Bedrijfslogo", no_logo: "Geen logo", upload_logo: "Logo uploaden", account: "Account", plan: "Plan", pro_unlim: "Pro — onbeperkt", free_limit: "Gratis — max 3 offertes", preferences: "Voorkeuren", language: "Taal", accent_color: "Huisstijlkleur", color_help: "Gebruikt in de header van je offerte- en factuur-PDF's." },
    billing: { title: "Abonnement", free: "Gratis", pro: "Pro", per_month: "/maand", current: "Huidig plan", active: "Actief", up_free: ["Max 3 offertes", "PDF-export", "E-mail bezorging", "Klantenbeheer"], up_pro: ["Onbeperkt offertes", "Onbeperkt facturen", "Premium PDF-lay-outs", "Alle gratis functies"], upgrade: "Upgrade naar Pro", redirecting: "Doorverwijzen…", confirming: "Betaling bevestigen…", test_note: "Testomgeving gebruikt Stripe-testkaart 4242 4242 4242 4242. Geen echte kosten." },
    auth: { welcome: "Welkom terug", subtitle: "Log in om je offertes te beheren", create_acc: "Maak je account", create_sub: "Begin binnen enkele minuten met professionele offertes", email: "E-mail", password: "Wachtwoord", name: "Naam", signin: "Inloggen", signing: "Inloggen…", creating: "Aanmaken…", create_btn: "Account aanmaken", new_to: "Nieuw bij Quotify?", create_link: "Account aanmaken", already: "Al geregistreerd?", signin_link: "Inloggen" },
  },
  de: {
    nav: { dashboard: "Dashboard", quotes: "Angebote", invoices: "Rechnungen", clients: "Kunden", billing: "Abrechnung", settings: "Einstellungen", new_quote: "Neues Angebot", logout: "Abmelden", free_plan: "Gratis", pro_plan: "Pro" },
    dash: { title: "Dashboard", total_quotes: "Angebote gesamt", sent: "Versendet", accepted: "Akzeptiert", declined: "Abgelehnt", paid_revenue: "Bezahlter Umsatz", unpaid: "Offen", overdue: "Überfällig", recent_quotes: "Letzte Angebote", view_all: "Alle anzeigen", no_quotes: "Noch keine Angebote. Erstelle dein erstes Angebot.", quotes_used: "Angebote im Gratis-Plan verwendet", upgrade_pro: "Auf Pro upgraden" },
    quote: { title: "Angebote", new: "Neues Angebot", edit: "Angebot bearbeiten", search_ph: "Suche nach Kunde oder Angebotsnummer", empty: "Noch keine Angebote.", no_match: "Keine passenden Angebote.", number: "Nummer", client: "Kunde", status: "Status", created: "Erstellt", total: "Gesamt", subtotal: "Zwischensumme", vat: "MwSt", discount: "Rabatt", project: "Projekt", project_ph: "Beschreibe das Projekt kurz", line_items: "Positionen", add_item: "Position hinzufügen", description: "Beschreibung", qty: "Menge", unit_price: "Einzelpreis", amount: "Betrag", notes: "Notizen", notes_ph: "Optionale Notizen", summary: "Übersicht", create: "Angebot erstellen", save: "Speichern", back: "Zurück", pdf: "PDF", send: "Senden", sending: "Senden…", convert_to_invoice: "In Rechnung umwandeln", convert_ready: "Bereit zur Rechnung?", convert_desc: "Dieses Angebot wurde akzeptiert. Wandle es in eine Rechnung um.", open_invoice: "Rechnung öffnen", status_block: "Status", status_desc: "Aktualisiere den Status nach Kundenrückmeldung", mark_accepted: "Akzeptiert", mark_declined: "Abgelehnt", reset_draft: "Zurück zu Entwurf", danger: "Gefahrenbereich", delete: "Angebot löschen", bill_to: "An", select_client: "Kunde wählen (optional)", new_client: "— Neuer Kunde —", client_name: "Kundenname", client_email: "E-Mail des Kunden", accent_color: "Akzentfarbe", applied_pdf: "Wird im PDF-Header verwendet" },
    discount: { title: "Rabatt", applied_before: "Vor MwSt angewendet", type: "Typ", value: "Wert", off: "Rabatt", none: "Kein Rabatt", percent: "Prozent (%)", fixed: "Fester Betrag (€)" },
    invoice: { title: "Rechnungen", search_ph: "Suche Kunde oder Rechnungsnr.", empty: "Noch keine Rechnungen.", no_match: "Keine passenden Rechnungen.", number: "Nummer", due_date: "Fälligkeit", revenue: "Gesamtumsatz", count: "Rechnungen", payment: "Zahlung", default_due: "Standard 30 Tage nach Erstellung", mark_paid: "Als bezahlt markieren", paid_on: "Bezahlt am", linked_quote: "Verknüpftes Angebot", danger: "Gefahrenbereich", delete: "Rechnung löschen" },
    clients: { title: "Kunden", add: "Kunde hinzufügen", new: "Neuer Kunde", edit: "Kunde bearbeiten", empty: "Noch keine Kunden.", name: "Name", email: "E-Mail", phone: "Telefon", company: "Firma", address: "Adresse", save: "Speichern", cancel: "Abbrechen" },
    settings: { title: "Einstellungen", save: "Speichern", saving: "Speichert…", company_info: "Firmendaten", company_name: "Firmenname", vat_number: "USt-IdNr.", phone: "Telefon", bank: "Bankkonto", address: "Adresse", signature: "E-Mail-Signatur", signature_help: "Erscheint am Ende jeder E-Mail und PDF.", logo: "Logo", no_logo: "Kein Logo", upload_logo: "Logo hochladen", account: "Konto", plan: "Plan", pro_unlim: "Pro — unbegrenzt", free_limit: "Gratis — max. 3 Angebote", preferences: "Einstellungen", language: "Sprache", accent_color: "Markenfarbe", color_help: "Wird im PDF-Header verwendet." },
    billing: { title: "Abrechnung", free: "Gratis", pro: "Pro", per_month: "/Monat", current: "Aktueller Plan", active: "Aktiv", up_free: ["Bis zu 3 Angebote", "PDF-Export", "E-Mail-Versand", "Kundenverwaltung"], up_pro: ["Unbegrenzte Angebote", "Unbegrenzte Rechnungen", "Premium-PDF-Layouts", "Alle Gratis-Funktionen"], upgrade: "Auf Pro upgraden", redirecting: "Weiterleitung…", confirming: "Zahlung wird bestätigt…", test_note: "Testumgebung verwendet Stripe-Testkarte 4242 4242 4242 4242." },
    auth: { welcome: "Willkommen zurück", subtitle: "Melde dich an, um deine Angebote zu verwalten", create_acc: "Konto erstellen", create_sub: "In Minuten professionelle Angebote senden", email: "E-Mail", password: "Passwort", name: "Name", signin: "Anmelden", signing: "Anmeldung…", creating: "Erstellen…", create_btn: "Konto erstellen", new_to: "Neu bei Quotify?", create_link: "Konto erstellen", already: "Schon registriert?", signin_link: "Anmelden" },
  },
  fr: {
    nav: { dashboard: "Tableau de bord", quotes: "Devis", invoices: "Factures", clients: "Clients", billing: "Abonnement", settings: "Paramètres", new_quote: "Nouveau devis", logout: "Déconnexion", free_plan: "Gratuit", pro_plan: "Pro" },
    dash: { title: "Tableau de bord", total_quotes: "Devis totaux", sent: "Envoyés", accepted: "Acceptés", declined: "Refusés", paid_revenue: "Revenu payé", unpaid: "Impayés", overdue: "En retard", recent_quotes: "Devis récents", view_all: "Voir tout", no_quotes: "Aucun devis. Créez votre premier devis.", quotes_used: "devis utilisés sur le plan Gratuit", upgrade_pro: "Passer au Pro" },
    quote: { title: "Devis", new: "Nouveau devis", edit: "Modifier le devis", search_ph: "Rechercher client ou numéro", empty: "Aucun devis.", no_match: "Aucun devis trouvé.", number: "Numéro", client: "Client", status: "Statut", created: "Créé", total: "Total", subtotal: "Sous-total", vat: "TVA", discount: "Remise", project: "Projet", project_ph: "Décrivez brièvement le projet", line_items: "Lignes", add_item: "Ajouter une ligne", description: "Description", qty: "Qté", unit_price: "Prix unitaire", amount: "Montant", notes: "Notes", notes_ph: "Notes optionnelles", summary: "Résumé", create: "Créer le devis", save: "Enregistrer", back: "Retour", pdf: "PDF", send: "Envoyer", sending: "Envoi…", convert_to_invoice: "Convertir en facture", convert_ready: "Prêt à facturer ?", convert_desc: "Ce devis a été accepté. Convertissez-le en facture.", open_invoice: "Ouvrir la facture", status_block: "Statut", status_desc: "Mettez à jour le statut après réponse du client", mark_accepted: "Marquer accepté", mark_declined: "Marquer refusé", reset_draft: "Remettre en brouillon", danger: "Zone dangereuse", delete: "Supprimer le devis", bill_to: "Facturer à", select_client: "Sélectionner un client", new_client: "— Nouveau client —", client_name: "Nom du client", client_email: "Email du client", accent_color: "Couleur d'accent", applied_pdf: "Appliquée à l'en-tête du PDF" },
    discount: { title: "Remise", applied_before: "Appliquée avant TVA", type: "Type", value: "Valeur", off: "Remise", none: "Sans remise", percent: "Pourcentage (%)", fixed: "Montant fixe (€)" },
    invoice: { title: "Factures", search_ph: "Rechercher client ou numéro de facture", empty: "Aucune facture.", no_match: "Aucune facture trouvée.", number: "Numéro", due_date: "Échéance", revenue: "Revenu total", count: "Factures", payment: "Paiement", default_due: "30 jours par défaut", mark_paid: "Marquer comme payée", paid_on: "Payée le", linked_quote: "Devis lié", danger: "Zone dangereuse", delete: "Supprimer la facture" },
    clients: { title: "Clients", add: "Ajouter un client", new: "Nouveau client", edit: "Modifier", empty: "Aucun client.", name: "Nom", email: "Email", phone: "Téléphone", company: "Société", address: "Adresse", save: "Enregistrer", cancel: "Annuler" },
    settings: { title: "Paramètres", save: "Enregistrer", saving: "Enregistrement…", company_info: "Informations société", company_name: "Nom de la société", vat_number: "N° TVA", phone: "Téléphone", bank: "Compte bancaire", address: "Adresse", signature: "Signature email", signature_help: "Apparaît au bas de chaque devis.", logo: "Logo", no_logo: "Aucun logo", upload_logo: "Uploader le logo", account: "Compte", plan: "Plan", pro_unlim: "Pro — illimité", free_limit: "Gratuit — 3 devis max", preferences: "Préférences", language: "Langue", accent_color: "Couleur de marque", color_help: "Utilisée dans l'en-tête des PDF." },
    billing: { title: "Abonnement", free: "Gratuit", pro: "Pro", per_month: "/mois", current: "Plan actuel", active: "Actif", up_free: ["Jusqu'à 3 devis", "Export PDF", "Envoi email", "Gestion clients"], up_pro: ["Devis illimités", "Factures illimitées", "Mises en page premium", "Toutes les fonctions gratuites"], upgrade: "Passer au Pro", redirecting: "Redirection…", confirming: "Confirmation du paiement…", test_note: "Environnement de test Stripe : 4242 4242 4242 4242." },
    auth: { welcome: "Bon retour", subtitle: "Connectez-vous pour gérer vos devis", create_acc: "Créer un compte", create_sub: "Envoyez des devis pros en quelques minutes", email: "Email", password: "Mot de passe", name: "Nom", signin: "Se connecter", signing: "Connexion…", creating: "Création…", create_btn: "Créer le compte", new_to: "Nouveau sur Quotify ?", create_link: "Créer un compte", already: "Déjà inscrit ?", signin_link: "Se connecter" },
  },
  es: {
    nav: { dashboard: "Panel", quotes: "Presupuestos", invoices: "Facturas", clients: "Clientes", billing: "Suscripción", settings: "Ajustes", new_quote: "Nuevo presupuesto", logout: "Cerrar sesión", free_plan: "Gratis", pro_plan: "Pro" },
    dash: { title: "Panel", total_quotes: "Presupuestos totales", sent: "Enviados", accepted: "Aceptados", declined: "Rechazados", paid_revenue: "Ingresos pagados", unpaid: "Pendientes", overdue: "Vencidas", recent_quotes: "Presupuestos recientes", view_all: "Ver todo", no_quotes: "Aún no hay presupuestos.", quotes_used: "presupuestos usados en el plan Gratis", upgrade_pro: "Pasar a Pro" },
    quote: { title: "Presupuestos", new: "Nuevo presupuesto", edit: "Editar presupuesto", search_ph: "Buscar cliente o número", empty: "Sin presupuestos.", no_match: "Sin resultados.", number: "Número", client: "Cliente", status: "Estado", created: "Creado", total: "Total", subtotal: "Subtotal", vat: "IVA", discount: "Descuento", project: "Proyecto", project_ph: "Describe el proyecto", line_items: "Líneas", add_item: "Añadir línea", description: "Descripción", qty: "Cant.", unit_price: "Precio unitario", amount: "Importe", notes: "Notas", notes_ph: "Notas opcionales", summary: "Resumen", create: "Crear presupuesto", save: "Guardar", back: "Atrás", pdf: "PDF", send: "Enviar", sending: "Enviando…", convert_to_invoice: "Convertir en factura", convert_ready: "¿Listo para facturar?", convert_desc: "Este presupuesto fue aceptado. Conviértelo en factura.", open_invoice: "Abrir factura", status_block: "Estado", status_desc: "Actualiza el estado tras la respuesta del cliente", mark_accepted: "Marcar aceptado", mark_declined: "Marcar rechazado", reset_draft: "Volver a borrador", danger: "Zona peligrosa", delete: "Eliminar presupuesto", bill_to: "Facturar a", select_client: "Elegir cliente", new_client: "— Nuevo cliente —", client_name: "Nombre del cliente", client_email: "Email del cliente", accent_color: "Color de acento", applied_pdf: "Se aplica en el encabezado del PDF" },
    discount: { title: "Descuento", applied_before: "Aplicado antes del IVA", type: "Tipo", value: "Valor", off: "Descuento", none: "Sin descuento", percent: "Porcentaje (%)", fixed: "Importe fijo (€)" },
    invoice: { title: "Facturas", search_ph: "Buscar cliente o número de factura", empty: "Aún no hay facturas.", no_match: "Sin resultados.", number: "Número", due_date: "Vencimiento", revenue: "Ingresos totales", count: "Facturas", payment: "Pago", default_due: "30 días por defecto", mark_paid: "Marcar pagada", paid_on: "Pagada el", linked_quote: "Presupuesto vinculado", danger: "Zona peligrosa", delete: "Eliminar factura" },
    clients: { title: "Clientes", add: "Añadir cliente", new: "Nuevo cliente", edit: "Editar", empty: "Sin clientes.", name: "Nombre", email: "Email", phone: "Teléfono", company: "Empresa", address: "Dirección", save: "Guardar", cancel: "Cancelar" },
    settings: { title: "Ajustes", save: "Guardar", saving: "Guardando…", company_info: "Información de la empresa", company_name: "Nombre de empresa", vat_number: "NIF / CIF", phone: "Teléfono", bank: "Cuenta bancaria", address: "Dirección", signature: "Firma de email", signature_help: "Aparece al final de cada presupuesto.", logo: "Logo", no_logo: "Sin logo", upload_logo: "Subir logo", account: "Cuenta", plan: "Plan", pro_unlim: "Pro — ilimitado", free_limit: "Gratis — 3 presupuestos máx", preferences: "Preferencias", language: "Idioma", accent_color: "Color de marca", color_help: "Se usa en el encabezado de los PDF." },
    billing: { title: "Suscripción", free: "Gratis", pro: "Pro", per_month: "/mes", current: "Plan actual", active: "Activo", up_free: ["Hasta 3 presupuestos", "Exportar PDF", "Envío por email", "Gestión de clientes"], up_pro: ["Presupuestos ilimitados", "Facturas ilimitadas", "Diseños PDF premium", "Todo lo de Gratis"], upgrade: "Pasar a Pro", redirecting: "Redirigiendo…", confirming: "Confirmando el pago…", test_note: "Entorno de prueba: Stripe 4242 4242 4242 4242." },
    auth: { welcome: "Bienvenido", subtitle: "Inicia sesión para gestionar tus presupuestos", create_acc: "Crear cuenta", create_sub: "Empieza a enviar presupuestos profesionales", email: "Email", password: "Contraseña", name: "Nombre", signin: "Iniciar sesión", signing: "Iniciando…", creating: "Creando…", create_btn: "Crear cuenta", new_to: "¿Nuevo en Quotify?", create_link: "Crear cuenta", already: "¿Ya registrado?", signin_link: "Iniciar sesión" },
  },
};

const I18nContext = createContext({ lang: "en", t: (k) => k, setLang: () => {} });

export function I18nProvider({ children }) {
  const { user } = useAuth();
  const [lang, setLangState] = useState(() => localStorage.getItem("quotify_lang") || "en");
  useEffect(() => {
    if (user?.language && user.language !== lang) {
      setLangState(user.language);
    }
    // eslint-disable-next-line
  }, [user?.language]);
  useEffect(() => { localStorage.setItem("quotify_lang", lang); document.documentElement.lang = lang; }, [lang]);
  const setLang = (l) => setLangState(l);
  const t = (key) => {
    const parts = key.split(".");
    let cur = dict[lang] || dict.en;
    for (const p of parts) { cur = cur?.[p]; if (cur === undefined) break; }
    if (cur === undefined) {
      cur = dict.en;
      for (const p of parts) cur = cur?.[p];
    }
    return cur ?? key;
  };
  return <I18nContext.Provider value={{ lang, setLang, t }}>{children}</I18nContext.Provider>;
}

export const useI18n = () => useContext(I18nContext);
